<s> Ok. I get the desired result if I use the command on all local files: cwm --closure=poEr myDingo.n3  </s>
<s> --think But I still get the error list below if I use the first command in your example: cwm --closure=por myDingo.n3  </s>
<s> --think That is, I get the error if I use closure flags 'por', but it works when I use closure flags 'poEr'.  </s>
<s> Whats the difference?  </s>
<s> 'E' does not appear in the list of closure flags in help.  </s>
<s> Thanks, John Black C:\Temp\cwm python /python23/lib/site-packages/cwm/cwm.py --closure=por myDingo.n3  </s>
<s> --think --filter=anyDogs.n3  </s>
<s> #Processed by Id: cwm.py,v 1.143.2.1 2003/09/12 14:56:21 timbl Exp # using base file:/Temp/cwm/myDingo.n3 Traceback (most recent call last): File "/python23/lib/site-packages/cwm/cwm.py", line 652, in ?  </s>
<s> doCommand() File "/python23/lib/site-packages/cwm/cwm.py", line 380, in doCommand p.load(_inputURI) File "C:\python23\lib\site-packages\cwm\notation3.py", line 209, in load return self.loadBuf(stream.read())  </s>
<s> # self._formula  </s>
<s> File "C:\python23\lib\site-packages\cwm\notation3.py", line 217, in loadBuf self.feed(buf)  </s>
<s> File "C:\python23\lib\site-packages\cwm\notation3.py", line 235, in feed i = self.directiveOrStatement(str,j)  </s>
<s> File "C:\python23\lib\site-packages\cwm\notation3.py", line 248, in directiveOrStatement j = self.statement(str,  </s>
<s> i) File "C:\python23\lib\site-packages\cwm\notation3.py", line 341, in statement j = self.property_list(str,  </s>
<s> i, r[0]) File "C:\python23\lib\site-packages\cwm\notation3.py", line 594, in property_list self.makeStatement((self._context, sym, subj, obj)) File "C:\python23\lib\site-packages\cwm\notation3.py", line 331, in makeStatement self._sink.makeStatement(quadruple,  </s>
<s> why=self._reason2)  </s>
<s> File "C:\python23\lib\site-packages\cwm\llyn.py", line 1452, in makeStatement self.storeQuad(q, why) File "C:\python23\lib\site-packages\cwm\llyn.py", line 1481, in storeQuad return context.add(subj=subj,  </s>
<s> pred=pred, obj=obj, why=why) File "C:\python23\lib\site-packages\cwm\llyn.py", line 479, in add self.checkClosure(subj, pred, obj) File "C:\python23\lib\site-packages\cwm\llyn.py", line 617, in checkClosure x.dereference("m" + self._closureMode, self) File "C:\python23\lib\site-packages\cwm\term.py", line 212, in dereference if "E" not in mode: F = self.store.load(inputURI)  </s>
<s> File "C:\python23\lib\site-packages\cwm\llyn.py", line 1263, in load p.feed(buffer) File "C:\python23\lib\site-packages\cwm\sax2rdf.py", line 584, in feed self._p.feed(data) File "C:\Python23\Lib\site-packages\_xmlplus\sax\expatreader.py", line 220, in feed self._err_handler.fatalError(exc)  </s>
<s> File "C:\Python23\Lib\site-packages\_xmlplus\sax\handler.py", line 38, in fatalError raise exception xml.sax._exceptions.SAXParseException:  </s>
<s> unknown :133:21: not well-formed (invalid token)  </s>
<s> From: Sandro Hawke [mailto:sandro@w3.org]  </s>
<s> Sent: Wednesday, October 08, 2003 1:33 PM Subject: Re: A bit of running code for "Tim's View" Sorry, I simplified the inputs slightly for the e-mail.  </s>
<s> I should have been clearer about that.  </s>
<s> The real files are in and I see that myDingo.n3 has a temporary patch "For working on the plane" (ie without the web handy).  </s>
<s> So yes, I left out the ":" prefix declaration.  </s>
<s> C:\Temp python /python23/lib/site-packages/cwm/cwm.py  </s>
<s> --closure=por myDingo.n  </s>
<s> 3 --think #Processed by Id: cwm.py,v 1.143.2.1 2003/09/12 14:56:21 timbl Exp # using base file:/Temp/myDingo.n3  </s>
<s> Traceback (most recent call last): File "/python23/lib/site-packages/cwm/cwm.py", line 652, in ?  </s>
<s> doCommand() File "/python23/lib/site-packages/cwm/cwm.py", line 380,  </s>
<s> in doCommand  </s>
<s> p.load(_inputURI) File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 209, in load  </s>
<s> return self.loadBuf(stream.read())  </s>
<s> # self._formula  </s>
<s> File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 217, in loadBuf  </s>
<s> self.feed(buf) File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 235, in feed  </s>
<s> i = self.directiveOrStatement(str,j)  </s>
<s> File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 248, in directi  </s>
<s> veOrStatement j = self.statement(str,  </s>
<s> i) File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 341, in stateme  </s>
<s> nt j = self.property_list(str,  </s>
<s> i, r[0]) File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 594, in propert  </s>
<s> y_list self.makeStatement((self._context, sym, subj, obj)) File "C:\python23\lib\site-packages\cwm\notation3.py",  </s>
<s> line 331, in makeSta  </s>
<s> tement self._sink.makeStatement(quadruple,  </s>
<s> why=self._reason2)  </s>
<s> File "C:\python23\lib\site-packages\cwm\llyn.py", line  </s>
<s> 1452, in makeStateme  </s>
<s> nt self.storeQuad(q, why) File "C:\python23\lib\site-packages\cwm\llyn.py", line  </s>
<s> 1481, in storeQuad  </s>
<s> return context.add(subj=subj,  </s>
<s> pred=pred, obj=obj, why=why) File "C:\python23\lib\site-packages\cwm\llyn.py", line 479, in add self.checkClosure(subj, pred, obj) File "C:\python23\lib\site-packages\cwm\llyn.py", line  </s>
<s> 617, in checkClosure  </s>
<s> x.dereference("m" + self._closureMode, self) File "C:\python23\lib\site-packages\cwm\term.py", line  </s>
<s> 212, in dereference  </s>
<s> if "E" not in mode: F = self.store.load(inputURI)  </s>
<s> File "C:\python23\lib\site-packages\cwm\llyn.py", line  </s>
<s> 1263, in load  </s>
<s> p.feed(buffer) File "C:\python23\lib\site-packages\cwm\sax2rdf.py", line  </s>
<s> 584, in feed  </s>
<s> self._p.feed(data) File  </s>
<s> "C:\Python23\Lib\site-packages\_xmlplus\sax\expatreader.py", line 216,  </s>
<s> in feed self._parser.Parse(data,  </s>
<s> isFinal) File  </s>
<s> "C:\Python23\Lib\site-packages\_xmlplus\sax\expatreader.py", line 395,  </s>
<s> in external_entity_ref self._source.getSystemId()  </s>
<s> or File  </s>
<s> "C:\Python23\Lib\site-packages\_xmlplus\sax\saxutils.py", line 515, in  </s>
<s> prepare_input_source f = urllib2.urlopen(source.getSystemId())  </s>
<s> File "c:\python23\lib\urllib2.py", line 136, in urlopen return _opener.open(url,  </s>
<s> data) File "c:\python23\lib\urllib2.py", line 331, in open type_ = req.get_type()  </s>
<s> File "c:\python23\lib\urllib2.py", line 233, in get_type raise ValueError, "unknown url type: %s" % self.__original  </s>
<s> ValueError: unknown url type: XMLSchema.dtd  </s>
<s> Hm. I don't know.  </s>
<s> Tim? (I've included him on the recipients) -- sandro  </s>
<s> (Tim?) I thought the E was the same as for --mode: to not report failure-to-retrieve as an error.  </s>
<s> So I dropped it from my example.  </s>
<s> But maybe I was wrong.  </s>
<s> :-/ -- sandro  </s>
<s> Yes, sorry forte lack of --help, E means ignore errors on retreive/parse.  </s>
