Please apply this patch to fix problems with the relativeURI function in notation3.py 
(thanks to Dan Connolly for the fix): 
diff -u -r1.82 notation3.py 
--- notation3.py 
2001/06/01 07:52:40 1.82 +++ notation3.py 
2001/06/22 03:49:49 @@ -1025,8 +1025,8 @@ if uri[i:i+1] =="#": return uri[i:] # fragment of base while i 0 and uri[i-1] != '/' : i=i-1 # scan for slash - if i == 0: return uri # No way. 
- if string.find(base, "//", i) 0: return uri # An unshared "//" + if i  3: return uri # No way. 
+ if string.find(base, "//", i-2) 0: return uri # An unshared "//" if string.find(base, ":", i) 0: return uri # An unshared ":" n = string.count(base, 
"/", i) return ("../" * n) + uri[i:] [ "Aaron Swartz" ; mailto:me@aaronsw.com ; http://www.aaronsw.com/ 
] 
fixed in $Id: notation3.py,v 
1.83 2001/06/25 06:35:50 connolly Exp $ see also test case 
cwm_test reluri-1.rdf 
"test generation of relative URIs" reluri-1.n3 
--rdf The patch below only fixed part of the problem, btw... 
Dan Connolly, W3C http://www.w3.org/People/Connolly/ 
Cleaning up cwm bug status... from 21 Jun 2001 This patch was applied and then the code was moved to uripath.py 
Dan Connolly, W3C http://www.w3.org/People/Connolly/ 
